- name: Provision EC2 instance and Install Jenkins
  hosts: localhost
  vars:
    image_id: "ami-016eb5d644c333ccb" # replace with your preffered image
    instance_type: "t2.micro" # replace with your preferred instance type
    key_name: "ansible_keys" # replace with your preferred key pair name
    region: "us-east-1" # replace with your preferred region
    subnet_id: "subnet-08ef7b3e735fe4487" # replace with your preferred subnet
    vpc_subnet_id: "vpc-0d8933cd63859a454" # replace with your preferred subnet
    security_groups: # replace with your preferred security group IDs
      - "sg-0ac99e5a037c06194"
      - "sg-0856fb08db7b466d0"
  tasks:
    - name: Create EC2 instance
      amazon.aws.ec2_instance:
        region: "{{ region }}"
        name: "jenkins_server"
        image_id: "{{ image_id }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ key_name }}"
        security_groups: "{{ security_groups }}"
        count: 1
        wait: yes
        subnet_id: "{{ subnet_id }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        filters:
          instance-state-name: running
          "tag:Name": "My EC2 Instance"
      register: running_instances

    - name: Add new host to inventory
      add_host:
        name: "{{ running_instances.instances[0].public_dns_name }}"
        groups: Server
        ansible_user: ec2-user
        ansible_ssh_private_key_file: /root/.ssh/ansible_keys.pem

    - name: Wait for system to become reachable
      ansible.builtin.wait_for_connection:
        timeout: 900
      delegate_to: "{{ running_instances.instances[0].public_dns_name }}"

    - name: Install Java
      become: true
      remote_user: ec2-user
      vars:
        ansible_ssh_private_key_file: /root/.ssh/ansible_keys.pem
      yum:
        name: java-1.8.0-openjdk-devel
        state: present

    - name: Install Jenkins
      become: true
      remote_user: ec2-user
      vars:
        ansible_ssh_private_key_file: /root/.ssh/ansible_keys.pem
      yum:
        name: wget
        state: present

    - name: Download Jenkins
      become: true
      remote_user: ec2-user
      vars:
        ansible_ssh_private_key_file: /root/.ssh/ansible_keys.pem
      get_url:
        url: https://updates.jenkins-ci.org/download/war/2.303/jenkins.war
        dest: /home/ec2-user/jenkins.war

    - name: Start Jenkins
      become: true
      remote_user: ec2-user
      vars:
        ansible_ssh_private_key_file: /root/.ssh/ansible_keys.pem
      shell: "nohup java -jar /home/ec2-user/jenkins.war > /dev/null 2>&1 &"

      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
